server:
  port: 1235
spring:
  application:
    name:
      BorrowService
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka,http://localhost:8802/eureka
feign:
  circuitbreaker:
    enable: true
management:
  endpoint:
    web:
      exposure:
        include: '*'